name: API CI/CD

on:
  pull_request:
    branches:
      - staging
      # - master

  push:
    branches:
      - staging
    tags:
      - 'v*'

jobs:

  # -------------------------
  # CI â€“ PR validation
  # -------------------------
  ci:
    if: |
      github.event_name == 'pull_request' ||
      startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: news_back_test_db
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; do
                echo "Waiting for MySQL..."
                sleep 2
              done

      - name: Run tests
        run: npm run test:ci

      - name: Build
        run: npm run build

  # -------------------------
  # STAGING 
  # -------------------------
  staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    needs: []

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: news_back_test_db
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build & push image (staging)
        run: |
          docker build --no-cache -t paulodev183883/admin-news-back-node:staging .
          docker push paulodev183883/admin-news-back-node:staging


      - name: Deploy to STAGING
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_SSH_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd ${{ secrets.STAGING_APP_PATH }}

            echo "Stopping service..."
            docker compose stop admin-node-news-service || true

            echo "Removing old image..."
            docker image rm -f paulodev183883/admin-news-back-node:staging || true

            echo "Pulling fresh image..."
            docker compose pull admin-node-news-service

            echo "Starting container..."
            docker compose \
              -f docker-compose.yml \
              -f docker-compose.staging.yml \
              up -d --no-deps --force-recreate admin-node-news-service
            
            echo "Waiting for container to stabilize..."
            sleep 10

            echo "Running migrations..."
            docker compose exec -T admin-node-news-service npm run migrate:latest-staging
            echo "Running seeds..."
            docker compose exec -T admin-node-news-service npm run seed:run-staging

  # -------------------------
  # PRODUCTION (TAG BASED)
  # -------------------------
  production:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: ci

    environment:
      name: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push image (production)
        run: |
          TAG=${GITHUB_REF#refs/tags/}

          docker build -t paulodev183883/admin-news-back-node:$TAG .
          docker tag paulodev183883/admin-news-back-node:$TAG paulodev183883/admin-news-back-node:latest

          docker push paulodev183883/admin-news-back-node:$TAG
          docker push paulodev183883/admin-news-back-node:latest

      - name: Deploy to PRODUCTION
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ${{ secrets.PROD_APP_PATH }}

            echo "Stopping service..."
            docker compose stop admin-node-news-service || true

            echo "Removing old image..."
            docker image rm -f paulodev183883/admin-news-back-node:latest || true

            docker compose \
              -f docker-compose.yml \
              -f docker-compose.prod.yml \
              --env-file .env.prod \
              up -d --no-deps --force-recreate admin-node-news-service
