name: API CI/CD

on:
  pull_request:
    branches:
      - staging
      # - master

  push:
    branches:
      - staging
    tags:
      - 'v*'

jobs:

  # -------------------------
  # CI â€“ PR validation
  # -------------------------
  ci:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: news_back_test_db
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; do
                echo "Waiting for MySQL..."
                sleep 2
              done

      - name: Run tests
        run: npm run test:ci

      - name: Build
        run: npm run build

  # -------------------------
  # STAGING 
  # -------------------------
  staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    needs: []

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: news_back_test_db
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build & push image (staging)
        run: |
          docker build --no-cache -t paulodev183883/admin-news-back-node:staging .
          docker tag paulodev183883/admin-news-back-node:staging paulodev183883/admin-news-back-node:latest

          docker push paulodev183883/admin-news-back-node:staging
          docker push paulodev183883/admin-news-back-node:latest


      - name: Deploy to STAGING
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_SSH_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd ${{ secrets.STAGING_APP_PATH }}
            docker compose pull admin-node-news-service

            docker compose \
              -f docker-compose.yml \
              -f docker-compose.staging.yml \
              up -d --no-deps --force-recreate admin-node-news-service

  # -------------------------
  # PRODUCTION (TAG BASED)
  # -------------------------
  production:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: news_back_test_db
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Prepare env
        run: cp .env.test .env

      - name: Test & Build
        run: |
          npm test
          npm run build

      - name: Deploy to PRODUCTION
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APP_PATH }}/prod
            docker compose pull
            docker compose up -d
